wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722412502
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 13
      - 23
      4: 3.12.3
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
